# Netlify configuration
[build]
  command = "npm run predeploy"
  publish = "dist"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect rules for React Router (SPA)
# Exclude Netlify functions from SPA redirect
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all rule for React Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
