# Netlify configuration
[build]
  command = "npm run predeploy"
  publish = "dist"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Webhook endpoints (don't redirect these)
[[redirects]]
  from = "/.netlify/functions/sumup-webhook"
  to = "/.netlify/functions/sumup-webhook"
  status = 200

[[redirects]]  
  from = "/.netlify/functions/payment-status-checker"
  to = "/.netlify/functions/payment-status-checker" 
  status = 200
