# Netlify configuration
[build]
  command = "npm run predeploy"
  publish = "dist"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect rules for React Router (SPA)
# Note: This should be the last rule to catch all non-function routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify functions are automatically available at /.netlify/functions/
# No redirect rules needed for function endpoints
