# Netlify configuration
[build]
  command = "npm run predeploy"
  publish = "dist"

# Netlify Functions configuration
[functions]
  directory = "netlify/functions"

# Redirect rules for React Router (SPA)
# Catch-all rule for React Router - functions are handled automatically by Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
